x-logging: &default-logging
  options:
    max-size: "50m"

volumes:
  postgres-validator-volume:
  redis-validator-volume:
  prisma-pip-cache:
  prisma-binary:

networks:
  dojo-validator:
    driver: bridge
  subtensor:
    name: subtensor

services:
  redis:
    extends:
      file: docker-compose.shared.yaml
      service: redis
    volumes:
      - redis-validator-volume:/data
    networks:
      - dojo-validator

  postgres:
    extends:
      file: docker-compose.shared.yaml
      service: postgres
    volumes:
      - postgres-validator-volume:/var/lib/postgresql/data
    networks:
      - dojo-validator

  synthetic-api:
    image: ghcr.io/tensorplex-labs/dojo-synthetic-api:main
    env_file:
      - .env
    expose:
      - 5003
    networks:
      - dojo-validator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://synthetic-api:5003/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      redis:
        condition: service_healthy
    # allow docker commands inside container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging: *default-logging

  prisma-setup-vali:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/Dockerfile.validator.prisma
    command: >
      sh -c "prisma migrate deploy && prisma generate"
    working_dir: /app
    volumes:
      - prisma-pip-cache:/root/.cache/pip
      - prisma-binary:/root/prisma-python
      - ./:/app
    networks:
      - dojo-validator
    depends_on:
      - postgres
    logging: *default-logging

  validator:
    image: ghcr.io/tensorplex-labs/dojo:main
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
      - ./.env:/app/.env
      - $BITTENSOR_DIR:/root/.bittensor
      - prisma-binary:/root/prisma-python
    command: ["validator"]
    networks:
      - dojo-validator
      - subtensor
    depends_on:
      synthetic-api:
        condition: service_healthy
      postgres:
        condition: service_healthy
      prisma-setup-vali:
        condition: service_completed_successfully
    logging: *default-logging